name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    #Define working directory for all the steps to run in workflow
    working-directory: ./web

jobs:

  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm install
    
    - name: 'Run Tests'
      run: npm run test

  lint:
    name: 'Run linter'
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
      name: 'Checkout repository'
    
    - name: 'Install Dependencies'
      run: npm install

    - name: 'Run Linter'
      run: npx standard -v