FROM node:16-alpine

# Create a app directory
WORKDIR /app

#Install app dependencies
COPY ../dist/package*.json ./

#RUN npm install
RUN npm install

COPY ../dist .

EXPOSE 3000

CMD [ "npm", "start" ]